// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image4":
            case "Temporary asset1":return img`
........................ffff....
................ffffffff..f.....
............ffffaaaaaaaaff......
.......fffffaaaaaaaaaaaf........
............ffffffffaff.........
...............feeeeffff........
..............feeeeeef..........
.............feeeeeeef..........
.............feefeefef..........
............ffeeeeeeef..........
......f.....f.feeeeef...........
.eee..fffffff.feeeffff..........
....eefaaaaaffffffaaaf..........
.....fffffffffffaaaaaf..........
............faaaaaaaaaf.........
............faaaaaaaaaf.........
...........faaaaaaaaaaaf........
...........faaaaaaaaaaaaf.f.....
..........faaaaaaaaaaaaaf.f.....
.........faaaaaaaaaaaaaaaff.....
.........faaaaaaaaaaaaaaaf......
........faaaaaaaaaaaaaaaaaf.....
........faaaaaaaaaaaffffff......
.......faaffffffffff............
....ffffff......................
................................
................................
................................
................................
................................
................................
................................
`;
            case "image3":
            case "Temporary asset0":return img`
....ffff........................
.....f..ffffffff................
......ffaaaaaaaaffff............
........faaaaaaaaaaafffff.......
.........ffaffffffff............
........ffffeeeef...............
..........feeeeeef...........1..
..........feeeeeeef.............
..........fefeefeef.............
..........feeeeeeeff............
...........feeeeef.f.....f......
..........ffffeeef.fffffff..eee.
..........faaaffffffaaaaafee....
..........faaaaafffffffffff.....
.........faaaaaaaaaf............
.........faaaaaaaaaf............
........faaaaaaaaaaaf...........
.....f.faaaaaaaaaaaaf...........
.....f.faaaaaaaaaaaaaf..........
.....ffaaaaaaaaaaaaaaaf.........
......faaaaaaaaaaaaaaaf.........
.....faaaaaaaaaaaaaaaaaf........
......ffffffaaaaaaaaaaaf........
............ffffffffffaaf.......
......................ffffff....
................................
................................
................................
................................
................................
................................
................................
`;
            case "image1":
            case "Temporary asset":return img`
........................ffff....
................ffffffff..f.....
............ffffaaaaaaaaff......
.......fffffaaaaaaaaaaaf........
............ffffffffaff.........
...............feeeeffff........
..............feeeeeef..........
.............feeeeeeef..........
.............feefeefef..........
............ffeeeeeeef..........
......f.....f.feeeeef...........
.eee..fffffff.feeeffff..........
....eefaaaaaffffffaaaf..........
.....fffffffffffaaaaaf..........
............faaaaaaaaaf.........
............faaaaaaaaaf.........
...........faaaaaaaaaaaf........
...........faaaaaaaaaaaaf.f.....
..........faaaaaaaaaaaaaf.f.....
.........faaaaaaaaaaaaaaaff.....
.........faaaaaaaaaaaaaaaf......
........faaaaaaaaaaaaaaaaaf.....
........faaaaaaaaaaaffffff......
.......faaffffffffff............
....ffffff......................
................................
................................
................................
................................
................................
................................
................................
`;
            case "image2":
            case "myImage":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . 2 2 . . . . . . . . . . 
. . . . . . 2 . . . . . . . . . 
. . . . . . . . 5 . . 2 . . . . 
. . . . . . . . 5 . 2 . . . . . 
. . . . . . 5 . . . . . . . . . 
. . . . . . 5 . . . . . . . . . 
. . . . . . . . . . . 5 . . . . 
. . . . . 2 . . 5 5 5 5 . . . . 
. . . . 2 . 5 5 . . . . . . . . 
. . . 2 2 . . 2 . . . . . . . . 
. . . 2 . . . . 2 . . . . . . . 
. . . . . . . . 2 2 2 2 . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image5":
            case "Temporary asset2":return img`
...................................
..........e........................
...........eee.....................
.............ee....................
......e.......ee..........11e......
......ee.eeeeeeeeeeeeeeeeeedeee....
........eedddddddddddddddddddde....
......eeeeeeeeeeeeeeeeeeeeedd55....
......e....eeeeeeeeeeeeeeeeee......
.............eeeeedddeeeeeee.......
..............eddddeeeee...........
.............eeeeee................
...........eeeeeee.................
.........eee.eee...................
.......eee..ee.....................
..........eee......................
`;
            case "image6":
            case "Temporary asset3":return img`
..........777777...................
........77777777777................
............777777777..............
..............77777777.....77......
...............77777777.....7......
...............777777777777772.....
..777........7777777777777777777...
.77.77....777..77777777777777...7..
.7...777777......77777.............
................777777.............
...............777777..............
..............7777777..............
..........7777.77777...............
.........7777777...................
...................................
...................................
`;
            case "image7":
            case "Temporary asset4":return img`
...................................
........................e..........
.....................eee...........
....................ee.............
......e11..........ee.......e......
....eeedeeeeeeeeeeeeeeeeee.ee......
....eddddddddddddddddddddee........
....55ddeeeeeeeeeeeeeeeeeeeee......
......eeeeeeeeeeeeeeeeee....e......
.......eeeeeeedddeeeee.............
...........eeeeedddde..............
................eeeeee.............
.................eeeeeee...........
...................eee.eee.........
.....................ee..eee.......
......................eee..........
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
