// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "myImage":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image4":
            case "Temporary asset1":return img`
........................ffff....
................ffffffff..f.....
............ffffaaaaaaaaff......
.......fffffaaaaaaaaaaaf........
............ffffffffaff.........
...............feeeeffff........
..............feeeeeef..........
.............feeeeeeef..........
.............feefeefef..........
............ffeeeeeeef..........
......f.....f.feeeeef...........
.eee..fffffff.feeeffff..........
....eefaaaaaffffffaaaf..........
.....fffffffffffaaaaaf..........
............faaaaaaaaaf.........
............faaaaaaaaaf.........
...........faaaaaaaaaaaf........
...........faaaaaaaaaaaaf.f.....
..........faaaaaaaaaaaaaf.f.....
.........faaaaaaaaaaaaaaaff.....
.........faaaaaaaaaaaaaaaf......
........faaaaaaaaaaaaaaaaaf.....
........faaaaaaaaaaaffffff......
.......faaffffffffff............
....ffffff......................
................................
................................
................................
................................
................................
................................
................................
`;
            case "image3":
            case "Temporary asset0":return img`
....ffff........................
.....f..ffffffff................
......ffaaaaaaaaffff............
........faaaaaaaaaaafffff.......
.........ffaffffffff............
........ffffeeeef...............
..........feeeeeef...........1..
..........feeeeeeef.............
..........fefeefeef.............
..........feeeeeeeff............
...........feeeeef.f.....f......
..........ffffeeef.fffffff..eee.
..........faaaffffffaaaaafee....
..........faaaaafffffffffff.....
.........faaaaaaaaaf............
.........faaaaaaaaaf............
........faaaaaaaaaaaf...........
.....f.faaaaaaaaaaaaf...........
.....f.faaaaaaaaaaaaaf..........
.....ffaaaaaaaaaaaaaaaf.........
......faaaaaaaaaaaaaaaf.........
.....faaaaaaaaaaaaaaaaaf........
......ffffffaaaaaaaaaaaf........
............ffffffffffaaf.......
......................ffffff....
................................
................................
................................
................................
................................
................................
................................
`;
            case "image1":
            case "Temporary asset":return img`
........................ffff....
................ffffffff..f.....
............ffffaaaaaaaaff......
.......fffffaaaaaaaaaaaf........
............ffffffffaff.........
...............feeeeffff........
..............feeeeeef..........
.............feeeeeeef..........
.............feefeefef..........
............ffeeeeeeef..........
......f.....f.feeeeef...........
.eee..fffffff.feeeffff..........
....eefaaaaaffffffaaaf..........
.....fffffffffffaaaaaf..........
............faaaaaaaaaf.........
............faaaaaaaaaf.........
...........faaaaaaaaaaaf........
...........faaaaaaaaaaaaf.f.....
..........faaaaaaaaaaaaaf.f.....
.........faaaaaaaaaaaaaaaff.....
.........faaaaaaaaaaaaaaaf......
........faaaaaaaaaaaaaaaaaf.....
........faaaaaaaaaaaffffff......
.......faaffffffffff............
....ffffff......................
................................
................................
................................
................................
................................
................................
................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
